[package]
name = "dynamecs-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynamecs-analyze = { path = "../dynamecs-analyze" }
tabwriter = "1.2.1"