[package]
name = "dynamecs-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version="4.3.0", features = [ "derive" ] }
dynamecs-analyze = { path = "../dynamecs-analyze" }
tabwriter = "1.2.1"
